name: "test"
on:  
 workflow_dispatch:
    inputs:
     who-to-greet:  # id of input
     description: 'Who to greet'
     required: true
     default: 'World'
     
jobs:
  test:
    runs-on: "windows-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v3"
    - name: "Read data from JSON file .github/workflows/parameter.json"
      uses: actions/github-script@v6
      id: read-json
      with:                  
          script: |
            let keyObject = {tanentName:"activenation",enVariable:"PROD"};
            const { TENANT_ID, BE_ENV } = process.env 
            const fs = require('fs');            
            const data = fs.readFileSync('.github/workflows/parameter.json');            
            const deploymentConfig = JSON.parse(data);
            let tenantConfigData = deploymentConfig[keyObject.tanentName][keyObject.enVariable];
            const LOCALYTICS_ID = tenantConfigData.localyticsId
            const FIRBASE_PROJECT_ID = tenantConfigData.firebaseProjectId
            const FIRBASE_SITE_ID = tenantConfigData.firebaseSiteId
            const FIRBASE_AUTH_KEY = tenantConfigData.firebaseAuthKey
            const FIRBASE_STRIPE_KEY = tenantConfigData.StripeKey

            if (LOCALYTICS_ID && LOCALYTICS_ID.length>0) {
              console.log('Found tenant name '+ keyObject['tanentName'] + ' and env '+ keyObject.enVariable);
              core.exportVariable('LOCALYTICS_ID', LOCALYTICS_ID)
            } else {
              const message = 'The LOCALYTICS_ID not found for tenant => ' + keyObject.tanentName + ' and environment => ' + keyObject.enVariable
              core.setFailed(message);
            }
             if (FIRBASE_PROJECT_ID && FIRBASE_PROJECT_ID.length>0) {
              console.log('Found tenant name '+ keyObject['tanentName'] + ' and env '+ keyObject.enVariable);
              core.exportVariable('FIRBASE_PROJECT_ID', FIRBASE_PROJECT_ID)
            } else {
              const message = 'The FIRBASE_PROJECT_ID not found for tenant => ' + keyObject.tanentName + ' and environment => ' + keyObject.enVariable
              core.setFailed(message);
            }
             if (FIRBASE_SITE_ID && FIRBASE_SITE_ID.length>0) {
              console.log('Found tenant name '+ keyObject['tanentName'] + ' and env '+ keyObject.enVariable);
              core.exportVariable('FIRBASE_SITE_ID', FIRBASE_SITE_ID)
            } else {
              const message = 'The FIRBASE_SITE_ID not found for tenant => ' + keyObject.tanentName + ' and environment => ' + keyObject.enVariable
              core.setFailed(message);
            }
             if (FIRBASE_AUTH_KEY && FIRBASE_AUTH_KEY.length>0) {
              console.log('Found tenant name '+ keyObject['tanentName'] + ' and env '+ keyObject.enVariable);
              core.exportVariable('FIRBASE_AUTH_KEY', FIRBASE_AUTH_KEY)
            } else {
              const message = 'The FIRBASE_AUTH_KEY not found for tenant => ' + keyObject.tanentName + ' and environment => ' + keyObject.enVariable
              core.setFailed(message);
            }
             if (FIRBASE_STRIPE_KEY && FIRBASE_STRIPE_KEY.length>0) {
              console.log('Found tenant name '+ keyObject['tanentName'] + ' and env '+ keyObject.enVariable);
              core.exportVariable('FIRBASE_STRIPE_KEY', FIRBASE_STRIPE_KEY)
            } else {
              const message = 'The FIRBASE_STRIPE_KEY not found for tenant => ' + keyObject.tanentName + ' and environment => ' + keyObject.enVariable
              core.setFailed(message);
            }
    - name: show resume.tex file content
      run: |
             node ./src/resume.js
      
     
      
