name: "test"
on:  
 push:
   branches: [ main ]
jobs:
  test:
    runs-on: "windows-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v3"
    - name: "Read data from JSON file .github/workflows/parameter.json"
      uses: actions/github-script@v6
      id: read-json
      with:                  
          script: |
            let keyObject = {tanentName:"activenation1",enVariable:"PROD"};
            const { TENANT_ID, BE_ENV } = process.env 
            const fs = require('fs');            
            const data = fs.readFileSync('.github/workflows/parameter.json');            
            const deploymentConfig = JSON.parse(data);
            console.log(`Reading data for tenant =>`+keyObject.tanentName); 
            let  getTenantInformation = ({tanentName,enVariable}) => {
            let tenantConfigData = deploymentConfig[tanentName][enVariable];
            if (tenantConfigData !=null) {
              console.log('Found tenant name '+ keyObject['tanentName'] + ' and env '+ keyObject.enVariable);
              const LOCALYTICS_ID = tenantObject.localyticsId;
              core.exportVariable('LOCALYTICS_ID', LOCALYTICS_ID)
            } else {
              const message = 'The tenant not found for tenant => ' + keyObject.tanentName + ' and environment => ' + keyObject.enVariable
              core.setFailed(message);
            }
            return tenantConfigData;
            };
            console.log(getTenantInformation(keyObject));
            let tenantObject = getTenantInformation(keyObject);
                 